{{- if .Values.mysqlInnodbcluster.useExternalSecret }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.ttp.secretName }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.mysqlInnodbcluster.secretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        # should contain all keys from {{ .Values.mysqlInnodbcluster.envSecret }} as well as 
        # keys ROOT_USER and ROOT_PASSWORD
        key: play-02-eks-02/zim/mysql-innodb-cluster/secret-env
{{- end }}
