apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ttp-app.fullname" . }}
  labels:
    app: {{ template "ttp-app.name" . }}
    chart: {{ template "ttp-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "ttp-app.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ttp-app.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          
          ports:
            - containerPort: {{ .Values.service.ports.http | default 8080 }}
              name: http
            - containerPort: {{ .Values.service.ports.mgmt | default 9990 }}
              name: mgmt
          
          env:
            - name: TZ
              value: {{ $.Values.timezone | quote }}
            
            # ENV
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            
            # Secret ENV
            {{- range $k, $v := .Values.envSecret }}
            - name: {{ $k }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.secretName }}
                  key: {{ $k }}
            {{- end }}
          
          command: {{ toJson .Values.entrypoint }}
          args: {{ toJson .Values.command }}

        {{- with .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
        {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}