{{- if .Values.useExternalSecret }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secretName }}
  labels:
    app: {{ template "ttp-app.name" . }}
    chart: {{ template "ttp-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        # Should contain all keys from .Values.envSecret
        key: {{ .Values.secretName }}
{{- end }}
