timezone: "Europe/Berlin"

replicaCount: 1

image: ghcr.io/vitagroup-ps/deployment-ttp:2025.1
imagePullSecrets:
  - name: ghcr-credentials
  
ingress:
  host: ttp
  tls:
    enabled: false
    secret: tls-secret-ref

service:
  type: ClusterIP
  ports:
    http: 8080
    mgmt: 9990
  
env:
  # Logging
  TTP_LOG_TO: "CONSOLE"
  TTP_LOG_LEVEL: "DEBUG"
  TTP_AUTH_LOG_TO: "CONSOLE"
  TTP_AUTH_LOG_LEVEL: "DEBUG"
  TTP_WEB_LOG_TO: "CONSOLE"
  TTP_WEB_LOG_LEVEL: "INFO"
  TTP_FHIR_LOG_TO: "CONSOLE"
  TTP_FHIR_LOG_LEVEL: "DEBUG"
  TTP_GPAS_LOG_TO: "CONSOLE"
  TTP_GPAS_LOG_LEVEL: "DEBUG"
  TTP_GICS_LOG_TO: "CONSOLE"
  TTP_GICS_LOG_LEVEL: "DEBUG"

  # Keycloak WEB
  TTP_GPAS_WEB_AUTH_MODE: "keycloak"
  TTP_GICS_WEB_AUTH_MODE: "keycloak"
  TTP_WEB_KEYCLOAK_REALM: "ttp"
  TTP_WEB_KEYCLOAK_SERVER_URL: "http://ttp-keycloak.ttp.svc.cluster.local:8091"
  TTP_WEB_KEYCLOAK_SSL_REQUIRED: "none"
  #TTP_WEB_KEYCLOAK_CONFIDENTIAL_PORT: 443

  # Keycloak SOAP
  TTP_GPAS_SOAP_KEYCLOAK_ENABLE: "true"
  TTP_GICS_SOAP_KEYCLOAK_ENABLE: "true"
  TTP_SOAP_KEYCLOAK_REALM: "ttp"
  TTP_SOAP_KEYCLOAK_SERVER_URL: "http://ttp-keycloak.ttp.svc.cluster.local:8091"
  TTP_SOAP_KEYCLOAK_SSL_REQUIRED: "none"
  #TTP_SOAP_KEYCLOAK_CONFIDENTIAL_PORT: 443

  # Keycloak FHIR
  TTP_FHIR_KEYCLOAK_ENABLE: "true"
  TTP_FHIR_KEYCLOAK_REALM: "ttp"
  TTP_FHIR_KEYCLOAK_SERVER_URL: "http://ttp-keycloak.ttp.svc.cluster.local:8091"
  TTP_FHIR_KEYCLOAK_SSL_REQUIRED: "none"
  #TTP_FHIR_KEYCLOAK_CONFIDENTIAL_PORT: 443

  # Keycloak Roles
  TTP_GPAS_SOAP_ROLE_USER_NAME: "role.gpas.soap.user"
  TTP_GPAS_SOAP_ROLE_ADMIN_NAME: "role.gpas.soap.admin"
  TTP_FHIR_KEYCLOAK_ROLE_GPAS_USER: "role.gpas.fhir.user"
  TTP_FHIR_KEYCLOAK_ROLE_GPAS_ADMIN: "role.gpas.fhir.admin"
  TTP_GICS_SOAP_ROLE_USER_NAME: "role.gics.soap.user"
  TTP_GICS_SOAP_ROLE_ADMIN_NAME: "role.gics.soap.admin"
  TTP_FHIR_KEYCLOAK_ROLE_GICS_USER: "role.gics.fhir.user"
  TTP_FHIR_KEYCLOAK_ROLE_GICS_ADMIN: "role.gics.fhir.admin"

  # gPAS
  TTP_GPAS_WEB_CONTEXT: "gpas-web"
  TTP_GPAS_SOAP_CONTEXT: "gpas"

  TTP_GPAS_DB_HOST: "ttp-mysql.ttp.svc.cluster.local"
  TTP_GPAS_DB_PORT: "3306"
  TTP_GPAS_DB_NAME: "gpas"

  # gICS
  TTP_GICS_WEB_CONTEXT: "gics-web"
  TTP_GICS_SOAP_CONTEXT: "gics"

  TTP_GICS_DB_HOST: "ttp-mysql.ttp.svc.cluster.local"
  TTP_GICS_DB_PORT: "3306"
  TTP_GICS_DB_NAME: "gics"

  # FHIR
  TTP_FHIR_GICS_ENDPOINT_ENABLED: "TRUE"
  TTP_FHIR_GPAS_ENDPOINT_ENABLED: "TRUE"

envSecret:
  # Keycloak WEB
  TTP_WEB_KEYCLOAK_CLIENT_ID: "" # value set by externalSecret
  TTP_WEB_KEYCLOAK_CLIENT_SECRET: "" # value set by externalSecret

  # Keycloak SOAP
  TTP_SOAP_KEYCLOAK_CLIENT_ID: "" # value set by externalSecret
  TTP_SOAP_KEYCLOAK_CLIENT_SECRET: "" # value set by externalSecret

  # Keycloak FHIR
  TTP_FHIR_KEYCLOAK_CLIENT_ID: "" # value set by externalSecret
  TTP_FHIR_KEYCLOAK_CLIENT_SECRET: "" # value set by externalSecret

  # gPAS
  TTP_GPAS_DB_USER: "" # value set by externalSecret
  TTP_GPAS_DB_PASS: "" # value set by externalSecret

  # gICS
  TTP_GICS_DB_USER: "" # value set by externalSecret
  TTP_GICS_DB_PASS: "" # value set by externalSecret

secretName: ttp-app-secret-ref-external
externalSecret:
  enabled: true
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  dataFrom:
    extract:
      key: ttp-app-secret-ref-external


entrypoint: ["/bin/bash"]
command: ["-c", "./wait-for-it.sh ttp-mysql.ttp.svc.cluster.local:3306 -t 120 && ./run.sh"]

resources: {}

nodeSelector: {}

affinity: {}

tolerations: []