apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ttp-keycloak.fullname" . }}
  labels:
    app: {{ template "ttp-keycloak.name" . }}
    chart: {{ template "ttp-keycloak.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "ttp-keycloak.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "ttp-keycloak.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: keycloak
          image: "{{ .Values.image }}"
          ports:
            - containerPort: {{ .Values.service.ports.http }}
              name: http
          env:
            - name: TZ
              value: {{ $.Values.timezone | quote }}
            
            # ENV
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            
            # Secret ENV
            {{- range $k, $v := .Values.envSecret }}
            - name: {{ $k }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Values.secretName }}
                  key: {{ $k }}
            {{- end }}

          volumeMounts:
            - name: {{ template "ttp-keycloak.fullname" . }}-realms
              mountPath: /opt/keycloak/data/import
              readOnly: true

          args: {{ toJson .Values.command }}
        
        {{- with .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
        {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      
      volumes:
        - name: {{ template "ttp-keycloak.fullname" . }}-realms
          configMap:
            name: {{ template "ttp-keycloak.fullname" . }}-realms
  