apiVersion: v1
kind: Service
metadata:
  name: {{ template "ttp-keycloak.fullname" . }}
  labels:
    app: {{ template "ttp-keycloak.fullname" . }}
    chart: {{ template "ttp-keycloak.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: {{ template "ttp-keycloak.fullname" . }}
    release: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.ports.http | default 8091 }}
      targetPort: 8091