apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  {{ .Values.ttp.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host:  {{ .Values.ttp.ingres.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ttp.name }}
                port:
                  number: {{ .Values.ttp.service.ports.http }}