{{- if not .Values.ttp.useExternalSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ttp.secretName }}
type: Opaque
data:
{{- range $k, $v := .Values.ttp.envSecret }}
  {{ $k }}: {{ $v | b64enc }}
{{- end }}
{{- end }}