apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ttp-keycloak.fullname" . }}-realms
  labels:
    app: {{ template "ttp-keycloak.name" . }}
    chart: {{ template "ttp-keycloak.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- $paths := .Files.Glob "realms/*.json" }}
{{- range $path, $_ := $paths }}
  {{ base $path }}: |
{{ tpl ($.Files.Get $path) $ | indent 4 }}
{{- end }}