apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.keycloak.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.keycloak.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.keycloak.name }}
    spec:
      containers:
        - name: keycloak
          image: "{{ .Values.keycloak.image }}"
          ports:
            - containerPort: {{ .Values.keycloak.service.ports.http }}
              name: http
          env:
            - name: TZ
              value: {{ $.Values.timezone | quote }}
            
            # ENV
            {{- range $k, $v := .Values.keycloak.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
            
            # Secret ENV
            {{- range $k, $v := .Values.keycloak.envSecret }}
            - name: {{ $k }}
              valueFrom:
                  secretKeyRef:
                    name: {{ $.Values.keycloak.secretName }}
                    key: {{ $k }}
            {{- end }}
          volumeMounts:
            - name: {{ .Values.keycloak.name }}-realms
              mountPath: /opt/keycloak/data/import
              readOnly: true
          args: {{ toJson .Values.keycloak.command }}
      volumes:
        - name: {{ .Values.keycloak.name }}-realms
          configMap:
            name: {{ .Values.keycloak.name }}-realms