{{- if not .Values.keycloak.useExternalSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloak.secretName }}
type: Opaque
data:
{{- range $k, $v := .Values.keycloak.envSecret }}
  {{ $k }}: {{ $v | b64enc }}
{{- end }}
{{- end }}