apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.keycloak.name }}
spec:
  type: {{ .Values.keycloak.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: {{ .Values.keycloak.name }}
  ports:
    - name: http
      port: {{ .Values.keycloak.service.ports.http | default 8091 }}
      targetPort: 8091